In [16]:
import torch

In [17]:
x = torch.rand(5, 5)
x

tensor([[0.0042, 0.8935, 0.2216, 0.8388, 0.9451],
        [0.4160, 0.0192, 0.4348, 0.5769, 0.5527],
        [0.3071, 0.6416, 0.3363, 0.0464, 0.6886],
        [0.0805, 0.0915, 0.7556, 0.3681, 0.1057],
        [0.7714, 0.6015, 0.7054, 0.8535, 0.4520]])

In [18]:
y = torch.eye(5)
y

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [19]:
x*y

tensor([[0.0042, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0192, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.3363, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.3681, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.4520]])

In [20]:
x+y

tensor([[1.0042, 0.8935, 0.2216, 0.8388, 0.9451],
        [0.4160, 1.0192, 0.4348, 0.5769, 0.5527],
        [0.3071, 0.6416, 1.3363, 0.0464, 0.6886],
        [0.0805, 0.0915, 0.7556, 1.3681, 0.1057],
        [0.7714, 0.6015, 0.7054, 0.8535, 1.4520]])