In [1]:
import torch

/Users/naii/Desktop/project/dsi441/env/lib/python3.7/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: numpy.core.multiarray failed to import (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}


In [10]:
x = torch.rand(5, 5)
x

tensor([[0.8214, 0.7751, 0.9023, 0.7167, 0.5637],
        [0.5151, 0.6552, 0.8391, 0.6489, 0.0590],
        [0.1878, 0.6639, 0.9363, 0.8056, 0.2907],
        [0.1702, 0.5325, 0.9389, 0.9210, 0.2039],
        [0.3922, 0.9605, 0.4143, 0.5472, 0.8225]])

In [11]:
y = torch.eye(5)
y

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
x*y

tensor([[0.8214, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.6552, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.9363, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.9210, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.8225]])

In [15]:
x+y

tensor([[1.8214, 0.7751, 0.9023, 0.7167, 0.5637],
        [0.5151, 1.6552, 0.8391, 0.6489, 0.0590],
        [0.1878, 0.6639, 1.9363, 0.8056, 0.2907],
        [0.1702, 0.5325, 0.9389, 1.9210, 0.2039],
        [0.3922, 0.9605, 0.4143, 0.5472, 1.8225]])